# Generated by Django 2.2.9 on 2022-02-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
