# Generated by Django 2.2.9 on 2022-02-22 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20220220_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedio',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vedio',
            name='key',
            field=models.CharField(max_length=20050, null=True),
        ),
    ]
